version: '2.4'
services:

  flask:
    build: .
    container_name: flask
    restart: unless-stopped
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://${MONGO_USER}:${MONGO_PASS}@mongodb:27017/${MONGO_DB}
    #volumes:
    #  - .:/app
    ports:
      - "8080:8080"

  mongodb:
    build: data/
    container_name: mongodb
    restart: unless-stopped
    environment:
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASS=${MONGO_PASS}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASS}
      - MONGO_INITDB_DATABASE=${MONGO_DB}
    volumes:
      - mongodb_server_data:/data/db
    command: mongod --serviceExecutor adaptive

volumes:
  mongodb_server_data:
